/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package.Views;

import Package.Data.ClienteData;
import javax.swing.JOptionPane;
import Package.Model.Cliente;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Milton Matias
 */
public class ClienteView extends javax.swing.JInternalFrame {
Cliente cliente;
ClienteData clienteData;
int acao;
    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
        try {
           cliente = new Cliente();
           clienteData = new ClienteData();
           acao = 0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Cliente = new javax.swing.JPanel();
        label_Nome = new javax.swing.JLabel();
        field_Nome = new javax.swing.JTextField();
        label_telefone = new javax.swing.JLabel();
        field_Telenone = new javax.swing.JTextField();
        label_Email = new javax.swing.JLabel();
        field_Email = new javax.swing.JTextField();
        field_Pesquisa = new javax.swing.JTextField();
        label_Id = new javax.swing.JLabel();
        Label_IdCliente = new javax.swing.JLabel();
        scrollPane_Cliente = new javax.swing.JScrollPane();
        Table_Cliente = new javax.swing.JTable();
        btn_Novo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_Pesquisar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        BackGround_Img = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1595, 858));

        Panel_Cliente.setLayout(null);

        label_Nome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_Nome.setForeground(new java.awt.Color(255, 255, 255));
        label_Nome.setText("Nome:");
        Panel_Cliente.add(label_Nome);
        label_Nome.setBounds(320, 100, 110, 29);

        field_Nome.setEditable(false);
        Panel_Cliente.add(field_Nome);
        field_Nome.setBounds(320, 140, 390, 40);

        label_telefone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_telefone.setForeground(new java.awt.Color(255, 255, 255));
        label_telefone.setText("Telefone:");
        Panel_Cliente.add(label_telefone);
        label_telefone.setBounds(320, 190, 130, 29);

        field_Telenone.setEditable(false);
        Panel_Cliente.add(field_Telenone);
        field_Telenone.setBounds(320, 230, 390, 40);

        label_Email.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_Email.setForeground(new java.awt.Color(255, 255, 255));
        label_Email.setText("Email:");
        Panel_Cliente.add(label_Email);
        label_Email.setBounds(320, 280, 80, 29);

        field_Email.setEditable(false);
        Panel_Cliente.add(field_Email);
        field_Email.setBounds(320, 310, 390, 40);

        field_Pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                field_PesquisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                field_PesquisaMouseEntered(evt);
            }
        });
        field_Pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_PesquisaKeyReleased(evt);
            }
        });
        Panel_Cliente.add(field_Pesquisa);
        field_Pesquisa.setBounds(480, 400, 600, 40);

        label_Id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_Id.setForeground(new java.awt.Color(204, 204, 204));
        label_Id.setText("ID:");
        Panel_Cliente.add(label_Id);
        label_Id.setBounds(750, 160, 60, 30);

        Label_IdCliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_IdCliente.setForeground(new java.awt.Color(204, 204, 204));
        Label_IdCliente.setText("0");
        Panel_Cliente.add(Label_IdCliente);
        Label_IdCliente.setBounds(800, 160, 160, 30);

        Table_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Cliente", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ClienteMouseClicked(evt);
            }
        });
        scrollPane_Cliente.setViewportView(Table_Cliente);

        Panel_Cliente.add(scrollPane_Cliente);
        scrollPane_Cliente.setBounds(310, 460, 1030, 310);

        btn_Novo.setText("Novo");
        btn_Novo.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });
        Panel_Cliente.add(btn_Novo);
        btn_Novo.setBounds(140, 500, 130, 40);

        btn_Salvar.setText("Salvar");
        btn_Salvar.setEnabled(false);
        btn_Salvar.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });
        Panel_Cliente.add(btn_Salvar);
        btn_Salvar.setBounds(140, 550, 130, 40);

        btn_Excluir.setText("Excluir");
        btn_Excluir.setEnabled(false);
        btn_Excluir.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_Excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ExcluirMouseClicked(evt);
            }
        });
        Panel_Cliente.add(btn_Excluir);
        btn_Excluir.setBounds(140, 650, 130, 40);

        btn_Pesquisar.setText("Pesquisar");
        Panel_Cliente.add(btn_Pesquisar);
        btn_Pesquisar.setBounds(320, 400, 140, 40);

        btn_Editar.setText("Editar");
        btn_Editar.setEnabled(false);
        btn_Editar.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditarMouseClicked(evt);
            }
        });
        Panel_Cliente.add(btn_Editar);
        btn_Editar.setBounds(140, 600, 130, 40);

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setEnabled(false);
        btn_Cancelar.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CancelarMouseClicked(evt);
            }
        });
        Panel_Cliente.add(btn_Cancelar);
        btn_Cancelar.setBounds(140, 700, 130, 40);

        BackGround_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Tela-Cadastrar-Cliente.png"))); // NOI18N
        BackGround_Img.setText("Nome:");
        Panel_Cliente.add(BackGround_Img);
        BackGround_Img.setBounds(0, 0, 1590, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        // TODO add your handling code here:
            limparCampos();//caso os campos estejam preenchidos
        
        field_Nome.setEditable(true);
        field_Telenone.setEditable(true);
        field_Email.setEditable(true);
        field_Pesquisa.setEditable(true);
        
        btn_Novo.setEnabled(false);
        btn_Salvar.setEnabled(true);
        btn_Excluir.setEnabled(false);
        btn_Editar.setEnabled(false);
        btn_Cancelar.setEnabled(true);
        acao = 1;
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        // TODO add your handling code here:
              try{
if(validarCampos()){
   if(preencherCliente()){
    if(acao == 1){
         if(clienteData.inserirRegistro(cliente)){
    
    JOptionPane.showMessageDialog(this,"Dados Salvos com sucesso!");
    limparCampos();//caso os campos estejam preenchidos
        
        field_Nome.setEditable(false);
        field_Telenone.setEditable(false);
        field_Email.setEditable(false);
        field_Pesquisa.setEditable(true);

        btn_Novo.setEnabled(true);
        btn_Salvar.setEnabled(false);
        btn_Excluir.setEnabled(false);
        btn_Editar.setEnabled(false);
        btn_Cancelar.setEnabled(false);

}else{
JOptionPane.showMessageDialog(this,"Falha ao inserir Registro!");
}//fim salvar
    }//fim iif acao 1
    if(acao == 2){
         if(clienteData.atualizar(cliente)){
    
    JOptionPane.showMessageDialog(this,"Dados Atualizados com sucesso!");
    limparCampos();//caso os campos estejam preenchidos

        
        field_Nome.setEditable(false);
        field_Telenone.setEditable(false);
        field_Email.setEditable(false);
        field_Email.setEditable(true);

        btn_Novo.setEnabled(true);
        btn_Salvar.setEnabled(false);
        btn_Excluir.setEnabled(false);
        btn_Editar.setEnabled(false);
        btn_Cancelar.setEnabled(false);

}else{
JOptionPane.showMessageDialog(this,"Falha ao Atualizar Registro!");
}//fim salvar
    }
//Salvar no banco de dados

   
  }//fim preencherObjetos
}//fim validarCampos

}catch(Exception erro){
      JOptionPane.showMessageDialog(this,"Erro ao Atualizar registro: "+erro.getMessage());
      }//fim catch
      
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void field_PesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_PesquisaKeyReleased
        try {
            if(field_Pesquisa.getText().length() > 0){
              String objetoPesquisa = field_Pesquisa.getText();
              Vector cabecalho = new Vector();
              cabecalho.add("ID");
              cabecalho.add("Nome do Cliente");
              cabecalho.add("Telefone");
              cabecalho.add("Email");
              Table_Cliente.setModel(new DefaultTableModel(clienteData.pesquisar(objetoPesquisa), cabecalho));

            }else{
              //Limpar Tabala
                Table_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Cliente", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erro ou pesquisar Cliente: "+e);
        }
    }//GEN-LAST:event_field_PesquisaKeyReleased

    private void Table_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ClienteMouseClicked
        int linha = Table_Cliente.getSelectedRow();
        if(linha > -1){
            String id_Cliente = Table_Cliente.getModel().getValueAt(linha,0).toString();
            String nome_Cliente = Table_Cliente.getModel().getValueAt(linha,1).toString();
            String nome_Telefone = Table_Cliente.getModel().getValueAt(linha,2).toString();
            String nome_Email = Table_Cliente.getModel().getValueAt(linha,3).toString();
            
            field_Nome.setEditable(false);
            field_Telenone.setEditable(false);
            field_Email.setEditable(false);
            field_Pesquisa.setEditable(true);
            
            Label_IdCliente.setText(id_Cliente);
            field_Nome.setText(nome_Cliente);
            field_Telenone.setText(nome_Telefone);
            field_Email.setText(nome_Email);
            
            btn_Excluir.setEnabled(true);
            btn_Editar.setEnabled(true);
            btn_Salvar.setEnabled(false);
            btn_Cancelar.setEnabled(true);
        }
    }//GEN-LAST:event_Table_ClienteMouseClicked

    private void btn_ExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExcluirMouseClicked
        try {
            if(!Label_IdCliente.getText().equals("")){
                if(JOptionPane.showConfirmDialog(this,
                        "Deseja Excluir Esse Registro",
                        "Excluir", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                if(clienteData.excluir(Integer.parseInt(Label_IdCliente.getText())))
                    JOptionPane.showMessageDialog(this,"Registro Excluido Com Sucesso!");
                    btn_CancelarMouseClicked(evt);
                
            }
                
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Excluir!: "+e.getMessage());
        }
    }//GEN-LAST:event_btn_ExcluirMouseClicked

    private void btn_EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditarMouseClicked
        // TODO add your handling code here:
        acao = 2;
        field_Nome.setEditable(true);
        field_Telenone.setEditable(true);
        field_Email.setEditable(true);
        field_Pesquisa.setEditable(false);
        
        btn_Novo.setEnabled(false);
        btn_Salvar.setEnabled(true);
        btn_Excluir.setEnabled(false);
        btn_Editar.setEnabled(false);
        btn_Cancelar.setEnabled(true);
    }//GEN-LAST:event_btn_EditarMouseClicked

    private void btn_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelarMouseClicked
         limparCampos();//caso os campos estejam preenchidos
        
        field_Nome.setEditable(false);
        field_Telenone.setEditable(false);
        field_Email.setEditable(false);
        field_Pesquisa.setEditable(true);
        
        btn_Novo.setEnabled(true);
        btn_Salvar.setEnabled(false);
        btn_Excluir.setEnabled(false);
        btn_Editar.setEnabled(false);
        btn_Cancelar.setEnabled(false);
        acao = 1;
    
    }//GEN-LAST:event_btn_CancelarMouseClicked

    private void field_PesquisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_field_PesquisaMouseEntered
       //efeitois de imagem
    }//GEN-LAST:event_field_PesquisaMouseEntered

    private void field_PesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_field_PesquisaMouseClicked
       //quando o mouse entrear no campo pesquisa
        field_Nome.setEditable(false);
        field_Telenone.setEditable(false);
        field_Email.setEditable(false);
        
        btn_Novo.setEnabled(true);
        btn_Salvar.setEnabled(false);
        btn_Excluir.setEnabled(false);
        btn_Editar.setEnabled(false);
        btn_Cancelar.setEnabled(true);
    }//GEN-LAST:event_field_PesquisaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround_Img;
    private javax.swing.JLabel Label_IdCliente;
    private javax.swing.JPanel Panel_Cliente;
    private javax.swing.JTable Table_Cliente;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JTextField field_Email;
    private javax.swing.JTextField field_Nome;
    private javax.swing.JTextField field_Pesquisa;
    private javax.swing.JTextField field_Telenone;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_Id;
    private javax.swing.JLabel label_Nome;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JScrollPane scrollPane_Cliente;
    // End of variables declaration//GEN-END:variables

public boolean validarCampos(){
if(field_Nome.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo Nome Cliente!");
      field_Nome.requestFocus();
      return false;//um campo obrigatório não foi preenchido, portanto, retornando false
                   //a informação "caracter vazio" não ira para o banco de dados
      }
      if(field_Telenone.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo Telefone!");
      field_Telenone.requestFocus();
      return false;
      }
      if(field_Email.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo Email!");
      Panel_Cliente.requestFocus();
      return false;
      }
    
        return true;
}//fim método ValidarCampos()

    private boolean preencherCliente() throws Exception{
      cliente = new Cliente();//pega atributos da classe que se deseja trabalhar EX: classe Cliente
      cliente.setIdCliente(Integer.parseInt(Label_IdCliente.getText()));
      cliente.setNomeCliente(field_Nome.getText());
      cliente.setTelefone(field_Telenone.getText());
      cliente.setEmail(field_Email.getText());
      return true;
      }

      private boolean limparCampos(){
      Label_IdCliente.setText("0");
      field_Nome.setText("");
      field_Telenone.setText("");
      field_Email.setText("");
      field_Pesquisa.setText("");
      
       
      
      
      //limpar linhas para tabela
       Table_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Cliente", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
      return true;
      }
 



}
