/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package.Views;

import Package.Data.JogoData;
import javax.swing.JOptionPane;
import Package.Model.Jogo;


/**
 *
 * @author Milton Matias
 */
public class JogoView extends javax.swing.JInternalFrame {

    Jogo jogo;// criando variável do tipo jogo...classe jogo
    JogoData jogoData;
    int acao;
    /**
     * Creates new form JogoView
     */
    public JogoView() {
      
        initComponents();
        try {
            jogo = new Jogo();
            jogoData = new JogoData();
            acao = 0;
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
        }
    }
      
  
//    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        Field_Nome = new javax.swing.JTextField();
        Field_Fabricante = new javax.swing.JTextField();
        Field_Ano_Lancamento = new javax.swing.JTextField();
        Field_Valor = new javax.swing.JTextField();
        Field_Exemplares = new javax.swing.JTextField();
        Field_Pesquisa = new javax.swing.JTextField();
        btn_Pesquisar = new javax.swing.JButton();
        btn_Fechar = new javax.swing.JButton();
        btn_Novo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_DarBaixa = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        Field_Id = new javax.swing.JTextField();
        Field_Categoria = new javax.swing.JTextField();
        NomeCompo = new javax.swing.JLabel();
        cbx_Status = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackGroundDeskTop = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        Field_Nome.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${jogoControl.jogoDigitado.nomeJogo}"), Field_Nome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(Field_Nome);
        Field_Nome.setBounds(180, 130, 400, 40);

        Field_Fabricante.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${jogoControl.jogoDigitado.fabricanteJogo}"), Field_Fabricante, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(Field_Fabricante);
        Field_Fabricante.setBounds(700, 130, 400, 40);

        Field_Ano_Lancamento.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${jogoControl.jogoDigitado.anoLancamentoJogo}"), Field_Ano_Lancamento, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(Field_Ano_Lancamento);
        Field_Ano_Lancamento.setBounds(710, 230, 180, 40);

        Field_Valor.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${jogoControl.jogoDigitado.valorJogo}"), Field_Valor, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(Field_Valor);
        Field_Valor.setBounds(970, 230, 180, 40);

        Field_Exemplares.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${jogoControl.jogoDigitado.exemplaresJogo}"), Field_Exemplares, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(Field_Exemplares);
        Field_Exemplares.setBounds(190, 310, 170, 40);
        jPanel1.add(Field_Pesquisa);
        Field_Pesquisa.setBounds(450, 420, 520, 40);

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Pesquisar);
        btn_Pesquisar.setBounds(990, 420, 140, 40);

        btn_Fechar.setText("Fechar");
        btn_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FecharActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Fechar);
        btn_Fechar.setBounds(1420, 700, 130, 50);

        btn_Novo.setText("Novo");
        btn_Novo.setPreferredSize(new java.awt.Dimension(75, 29));
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Novo);
        btn_Novo.setBounds(130, 480, 150, 50);

        btn_Salvar.setText("Salvar");
        btn_Salvar.setEnabled(false);
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Salvar);
        btn_Salvar.setBounds(130, 540, 150, 50);

        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Editar);
        btn_Editar.setBounds(130, 600, 150, 50);

        btn_Excluir.setText("Excluir");
        btn_Excluir.setEnabled(false);
        jPanel1.add(btn_Excluir);
        btn_Excluir.setBounds(130, 660, 150, 50);

        btn_DarBaixa.setText("Dar Baixa");
        btn_DarBaixa.setEnabled(false);
        jPanel1.add(btn_DarBaixa);
        btn_DarBaixa.setBounds(130, 730, 150, 50);

        btn_cancelar.setText("Cancelar");
        jPanel1.add(btn_cancelar);
        btn_cancelar.setBounds(1140, 420, 140, 40);

        Field_Id.setText("0");
        Field_Id.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${jogoControl.jogoDigitado.idJogo}"), Field_Id, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(Field_Id);
        Field_Id.setBounds(480, 310, 140, 40);

        Field_Categoria.setEditable(false);
        jPanel1.add(Field_Categoria);
        Field_Categoria.setBounds(180, 230, 290, 40);

        NomeCompo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NomeCompo.setForeground(new java.awt.Color(255, 255, 255));
        NomeCompo.setText("Status");
        jPanel1.add(NomeCompo);
        NomeCompo.setBounds(490, 200, 70, 22);

        cbx_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Selecionar Status>>", "Disponível", "Indisponível" }));
        jPanel1.add(cbx_Status);
        cbx_Status.setBounds(490, 230, 200, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Fabricante", "Ano", "Categoria", "Valor Aluguel", "Status", "Exemplares", "Data Cadastro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 480, 1060, 310);

        BackGroundDeskTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Tela-Cadastrar-Listar-Jogos.png"))); // NOI18N
        jPanel1.add(BackGroundDeskTop);
        BackGroundDeskTop.setBounds(0, 0, 1580, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_FecharActionPerformed

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        // TODO add your handling code here:
        limparCampos();//caso os campos estejam preenchidos
        Field_Id.setEditable(true);
        Field_Nome.setEditable(true);
        Field_Fabricante.setEditable(true);
        Field_Categoria.setEditable(true);
        Field_Valor.setEditable(true);
        Field_Exemplares.setEditable(true);
        Field_Ano_Lancamento.setEditable(true);
        boolean b = true;
        cbx_Status.setEnabled(b);
        btn_Novo.setEnabled(false);
        btn_Salvar.setEnabled(true);
        btn_Excluir.setEnabled(true);
        acao = 1;
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
      try{
if(validarCampos()){
   if(preencherJogo()){
    if(acao == 1){
       //Salvar no banco de dados
   if(jogoData.inserirRegistro(jogo)){

    JOptionPane.showMessageDialog(this,"Dados Salvos com sucesso!");
    limparCampos();//caso os campos estejam preenchidos

        Field_Id.setEditable(false);
        Field_Nome.setEditable(false);
        Field_Fabricante.setEditable(false);
        Field_Categoria.setEditable(false);
        Field_Valor.setEditable(false);
        Field_Exemplares.setEditable(false);
        Field_Ano_Lancamento.setEditable(false);
        boolean b = false;
        cbx_Status.setEnabled(b);

btn_Novo.setEnabled(true);
btn_Salvar.setEnabled(false);
btn_Excluir.setEnabled(false);

}else{
JOptionPane.showMessageDialog(this,"Falha ao inserir Registro!");
} 
    }//fim if acao 1

    if(acao == 2){
       //Salvar no banco de dados
   if(jogoData.atualizar(jogo)){

    JOptionPane.showMessageDialog(this,"Dados Salvos com sucesso!");
    limparCampos();//caso os campos estejam preenchidos

        Field_Id.setEditable(false);
        Field_Nome.setEditable(false);
        Field_Fabricante.setEditable(false);
        Field_Categoria.setEditable(false);
        Field_Valor.setEditable(false);
        Field_Exemplares.setEditable(false);
        Field_Ano_Lancamento.setEditable(false);
        boolean b = false;
        cbx_Status.setEnabled(b);

btn_Novo.setEnabled(true);
btn_Salvar.setEnabled(false);
btn_Excluir.setEnabled(false);

}else{
JOptionPane.showMessageDialog(this,"Falha ao inserir Registro!");
} 
    }//fim if acao 2

  }//fim preencherObjetos
}//fim validarCampos

}catch(Exception erro){
      JOptionPane.showMessageDialog(this,"erro ao salvar registro: "+erro.getMessage());
      }//fim catch
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        // TODO add your handling code here:
        if(Field_Pesquisa.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo  pesquisa!");
      Field_Pesquisa.requestFocus();
 
      }
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        // TODO add your handling code here:
        acao = 2;
    }//GEN-LAST:event_btn_EditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundDeskTop;
    private javax.swing.JTextField Field_Ano_Lancamento;
    private javax.swing.JTextField Field_Categoria;
    private javax.swing.JTextField Field_Exemplares;
    private javax.swing.JTextField Field_Fabricante;
    private javax.swing.JTextField Field_Id;
    private javax.swing.JTextField Field_Nome;
    private javax.swing.JTextField Field_Pesquisa;
    private javax.swing.JTextField Field_Valor;
    private javax.swing.JLabel NomeCompo;
    private javax.swing.JButton btn_DarBaixa;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Fechar;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox<String> cbx_Status;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    
       private boolean validarCampos(){

      if(Field_Nome.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo Nome!");
      Field_Nome.requestFocus();
      return false;//um campo obrigatório não foi preenchido, portanto, retornando false
                   //a informação "caracter vazio" não ira para o banco de dados
      }
      if(Field_Fabricante.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo Nome fabricante!");
      Field_Fabricante.requestFocus();
      return false;
      }
      
      if(Field_Valor.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo valor!");
      Field_Valor.requestFocus();
      return false;
      }
      if(Field_Exemplares.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo exemplares!");
      Field_Exemplares.requestFocus();
      return false;
      }
      if(Field_Ano_Lancamento.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo ano de lançamento!");
      Field_Ano_Lancamento.requestFocus();
      return false;
      }

      //validar comboBox
      if(Field_Categoria.getText().equals("")){
      JOptionPane.showMessageDialog(this,"Favor preencher campo Categoria!");
      Field_Categoria.requestFocus();
      return false;
      }

      return true;
      }//fim método validarCampos

        private boolean preencherJogo() throws Exception{
      jogo = new Jogo();//pega atributos da classe que se deseja trabalhar EX: classe Cliente
      jogo.setIdJogo(Integer.parseInt(Field_Id.getText()));
      jogo.setNomeJogo(Field_Nome.getText());
      jogo.setFabricanteJogo(Field_Fabricante.getText());
      jogo.setAnoLancamentoJogo(Field_Ano_Lancamento.getText());
      jogo.setCategoriaJogo(Field_Categoria.getText());
      jogo.setValorAluguelJogo(Double.parseDouble(Field_Valor.getText()));
      jogo.setStatusJogo(cbx_Status.getSelectedIndex());
      jogo.setExemplaresJogo(Field_Exemplares.getText());
      return true;
      }

      private boolean limparCampos(){
      Field_Id.setText("0");
      Field_Nome.setText("");
      Field_Fabricante.setText("");
      Field_Categoria.setText("");
      Field_Valor.setText("");
      Field_Exemplares.setText("");
      Field_Ano_Lancamento.setText("");
      cbx_Status.setSelectedIndex(0);
      return true;
      }
 
}//-------------------------------------------------------------------------------
