/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package.Views;

import javax.swing.JOptionPane;
import Package.Control.LocacaoControl;
import Package.Data.LocacaoData;
import Package.Model.Locacao;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Milton Matias
 */
public class LocacaoView extends javax.swing.JInternalFrame {
Locacao locacao;
LocacaoControl locacaoControl;
LocacaoData locacaoDada;
int acao;
boolean resultado;
    /**
     * Creates new form LocacaoView
     */
    public LocacaoView() {
        initComponents();
        try {
            locacao = new Locacao();
            locacaoControl = new LocacaoControl();
            locacaoDada = new LocacaoData();
            acao = 0;
            resultado = false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Novo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Fechar = new javax.swing.JButton();
        field_ValorAluguel = new javax.swing.JTextField();
        field_DataLocacao = new javax.swing.JTextField();
        field_DataDevolucao = new javax.swing.JTextField();
        field_IdItensLocacao = new javax.swing.JTextField();
        field_IdCliente = new javax.swing.JTextField();
        label_ID = new javax.swing.JLabel();
        label_IdLocacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Locacao = new javax.swing.JTable();
        field_Pesquisar = new javax.swing.JTextField();
        btn_Pesquisa = new javax.swing.JButton();
        label_NomeCliente = new javax.swing.JLabel();
        label_IdItem = new javax.swing.JLabel();
        label_ValorAluguel = new javax.swing.JLabel();
        label_dtDevolucao = new javax.swing.JLabel();
        label_DataLocacao = new javax.swing.JLabel();
        Label_BackGroundImg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1595, 858));

        jPanel1.setLayout(null);

        btn_Novo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Novo.setText("Novo");
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Novo);
        btn_Novo.setBounds(120, 490, 150, 50);

        btn_Salvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Salvar.setText("Salvar");
        btn_Salvar.setEnabled(false);
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Salvar);
        btn_Salvar.setBounds(120, 550, 150, 50);

        btn_Editar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Editar.setText("Editar");
        btn_Editar.setEnabled(false);
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Editar);
        btn_Editar.setBounds(120, 610, 150, 50);

        btn_Excluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Excluir.setText("Excluir");
        btn_Excluir.setEnabled(false);
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Excluir);
        btn_Excluir.setBounds(120, 670, 150, 50);

        btn_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setEnabled(false);
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancelar);
        btn_Cancelar.setBounds(120, 730, 150, 50);

        btn_Fechar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Fechar.setText("Fechar");
        btn_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FecharActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Fechar);
        btn_Fechar.setBounds(1390, 740, 150, 50);

        field_ValorAluguel.setEditable(false);
        jPanel1.add(field_ValorAluguel);
        field_ValorAluguel.setBounds(230, 170, 190, 40);

        field_DataLocacao.setEditable(false);
        jPanel1.add(field_DataLocacao);
        field_DataLocacao.setBounds(670, 170, 190, 40);

        field_DataDevolucao.setEditable(false);
        jPanel1.add(field_DataDevolucao);
        field_DataDevolucao.setBounds(450, 170, 190, 40);

        field_IdItensLocacao.setEditable(false);
        jPanel1.add(field_IdItensLocacao);
        field_IdItensLocacao.setBounds(660, 270, 400, 40);

        field_IdCliente.setEditable(false);
        jPanel1.add(field_IdCliente);
        field_IdCliente.setBounds(230, 270, 400, 40);

        label_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_ID.setForeground(new java.awt.Color(204, 204, 204));
        label_ID.setText("Código:");
        jPanel1.add(label_ID);
        label_ID.setBounds(890, 180, 80, 22);

        label_IdLocacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_IdLocacao.setForeground(new java.awt.Color(204, 204, 204));
        label_IdLocacao.setText("0");
        jPanel1.add(label_IdLocacao);
        label_IdLocacao.setBounds(980, 180, 97, 22);

        Table_Locacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Valor da Locação", "Data da Locação", "Data de Devolução", "ID do Item", "ID do Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Locacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_LocacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Locacao);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(310, 460, 1040, 330);

        field_Pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_PesquisarKeyReleased(evt);
            }
        });
        jPanel1.add(field_Pesquisar);
        field_Pesquisar.setBounds(410, 400, 540, 40);

        btn_Pesquisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Pesquisa.setText("Pesquisar");
        jPanel1.add(btn_Pesquisa);
        btn_Pesquisa.setBounds(970, 400, 140, 40);

        label_NomeCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_NomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        label_NomeCliente.setText("ID do Cliente:");
        jPanel1.add(label_NomeCliente);
        label_NomeCliente.setBounds(230, 240, 140, 22);

        label_IdItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_IdItem.setForeground(new java.awt.Color(255, 255, 255));
        label_IdItem.setText("ID Item:");
        jPanel1.add(label_IdItem);
        label_IdItem.setBounds(660, 240, 80, 22);

        label_ValorAluguel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_ValorAluguel.setForeground(new java.awt.Color(255, 255, 255));
        label_ValorAluguel.setText("Valor da Locação:");
        jPanel1.add(label_ValorAluguel);
        label_ValorAluguel.setBounds(230, 140, 160, 22);

        label_dtDevolucao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_dtDevolucao.setForeground(new java.awt.Color(255, 255, 255));
        label_dtDevolucao.setText("Data da Devolução:");
        jPanel1.add(label_dtDevolucao);
        label_dtDevolucao.setBounds(450, 140, 177, 22);

        label_DataLocacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_DataLocacao.setForeground(new java.awt.Color(255, 255, 255));
        label_DataLocacao.setText("Data da Locação:");
        jPanel1.add(label_DataLocacao);
        label_DataLocacao.setBounds(670, 140, 190, 22);

        Label_BackGroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Tela-Cadastrar-Cliente.png"))); // NOI18N
        jPanel1.add(Label_BackGroundImg);
        Label_BackGroundImg.setBounds(-10, 0, 1580, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1553, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        // TODO add your handling code here:
        limparCampos();
        field_ValorAluguel.setEditable(true);
        field_DataLocacao.setEditable(true);
        field_DataDevolucao.setEditable(true);
        field_IdItensLocacao.setEditable(true);
        field_IdCliente.setEditable(true);
        
        btn_Salvar.setEnabled(true);
        btn_Editar.setEnabled(false);
        btn_Excluir.setEnabled(false);
        btn_Cancelar.setEnabled(true);
        acao = 1;
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FecharActionPerformed
        this.dispose();// fechar janela
    }//GEN-LAST:event_btn_FecharActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
         if(validarCampos()){
            try {                        
            if(preencherLocacao()){
               if(locacaoControl.salvarAtualizarRegistroLocacao(locacao, acao)){
                limparCampos();//caso os campos estejam preenchidos        
                salvarDesabilitarBotoesCampos();
               }else{
        JOptionPane.showMessageDialog(this,"Falha ao Salvar Registro!");           
               }//fim               
            }//fim preencherCliente
            } catch (Exception e) {
        JOptionPane.showMessageDialog(this,"Erro: "+e.getMessage());         
            }
        }//fim if(validarCampos()) 
        
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void field_PesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_PesquisarKeyReleased
        try {
            if(field_Pesquisar.getText().length() > 0){
                Integer objetoPesquisa = Integer.parseInt(field_Pesquisar.getText());
                
              Vector cabecalho = new Vector();
              cabecalho.add("ID");
              cabecalho.add("Valor da Locação");
              cabecalho.add("Data da Locação");
              cabecalho.add("Data da Devolução");
              cabecalho.add("ID do Item");
              cabecalho.add("ID do Cliente");
              Table_Locacao.setModel(new DefaultTableModel(locacaoDada.pesquisarRegistroLocacao(objetoPesquisa), cabecalho));
            }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this,"Erro ou pesquisar Locação: "+e);
        }
    }//GEN-LAST:event_field_PesquisarKeyReleased

    private void Table_LocacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_LocacaoMouseClicked
        int linha = Table_Locacao.getSelectedRow();
        if(linha > -1){
            String id_Locacao = Table_Locacao.getModel().getValueAt(linha,0).toString();
            String valorLocacao = Table_Locacao.getModel().getValueAt(linha,1).toString(); 
            String dataLocacao = Table_Locacao.getModel().getValueAt(linha,2).toString();
            String dataDevolucao = Table_Locacao.getModel().getValueAt(linha,3).toString();
            String idItem = Table_Locacao.getModel().getValueAt(linha,4).toString();
            String idCliente = Table_Locacao.getModel().getValueAt(linha,5).toString();
            
            label_IdLocacao.setText(id_Locacao);
            field_ValorAluguel.setText(valorLocacao);
            field_DataLocacao.setText(dataLocacao);
            field_DataDevolucao.setText(dataDevolucao);
            field_IdItensLocacao.setText(idItem);
            field_IdCliente.setText(idCliente);
            
            field_ValorAluguel.setEditable(false);
            field_DataLocacao.setEditable(false);
            field_DataDevolucao.setEditable(false);
            field_IdItensLocacao.setEditable(false);
            field_IdCliente.setEditable(false);
            
               
            btn_Excluir.setEnabled(true);
            btn_Editar.setEnabled(true);
            btn_Salvar.setEnabled(false);
            btn_Cancelar.setEnabled(true);
        }
    }//GEN-LAST:event_Table_LocacaoMouseClicked

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
       acao = 2;
            field_ValorAluguel.setEditable(true);
            field_DataLocacao.setEditable(true);
            field_DataDevolucao.setEditable(true);
            field_IdItensLocacao.setEditable(true);
            field_IdCliente.setEditable(true);
            
            btn_Excluir.setEnabled(true);
            btn_Editar.setEnabled(false);
            btn_Salvar.setEnabled(true);
            btn_Cancelar.setEnabled(true);
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        if(!label_IdLocacao.getText().equals("")){
        resultado = locacaoControl.exclirRegistroLocacao(Integer.parseInt(label_IdLocacao.getText()));
         if(resultado == false){
             
         }
        }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
            limparCampos();
            field_ValorAluguel.setEditable(false);
            field_DataLocacao.setEditable(false);
            field_DataDevolucao.setEditable(false);
            field_IdItensLocacao.setEditable(false);
            field_IdCliente.setEditable(false);
            
            btn_Novo.setEnabled(true);
            btn_Excluir.setEnabled(false);
            btn_Editar.setEnabled(false);
            btn_Salvar.setEnabled(false);
            btn_Cancelar.setEnabled(false);
    }//GEN-LAST:event_btn_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_BackGroundImg;
    private javax.swing.JTable Table_Locacao;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Fechar;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Pesquisa;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JTextField field_DataDevolucao;
    private javax.swing.JTextField field_DataLocacao;
    private javax.swing.JTextField field_IdCliente;
    private javax.swing.JTextField field_IdItensLocacao;
    private javax.swing.JTextField field_Pesquisar;
    private javax.swing.JTextField field_ValorAluguel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_DataLocacao;
    private javax.swing.JLabel label_ID;
    private javax.swing.JLabel label_IdItem;
    private javax.swing.JLabel label_IdLocacao;
    private javax.swing.JLabel label_NomeCliente;
    private javax.swing.JLabel label_ValorAluguel;
    private javax.swing.JLabel label_dtDevolucao;
    // End of variables declaration//GEN-END:variables

public boolean validarCampos(){
    if(field_ValorAluguel.getText().equals("")){
       JOptionPane.showMessageDialog(this,"Favor preencher campo valor da locação!");
        field_ValorAluguel.requestFocus();
    }
    if(field_DataDevolucao.getText().equals("")){
       JOptionPane.showMessageDialog(this,"Favor preencher campo data de Devolução!");
        field_DataDevolucao.requestFocus();
    }
    if(field_IdItensLocacao.getText().equals("")){
       JOptionPane.showMessageDialog(this,"Favor preencher campo ID Itens da locação!");
        field_IdItensLocacao.requestFocus();
    }
    if(field_IdCliente.getText().equals("")){
       JOptionPane.showMessageDialog(this,"Favor preencher campo ID Cliente!");
        field_IdCliente.requestFocus();
    }
    
    return true;
}//Fim validarCampos()

public boolean preencherLocacao()throws Exception{
   locacao = new Locacao();
   locacao.setIdLocacao(Integer.parseInt(label_IdLocacao.getText()));
   locacao.setValorTotalLocacao(Double.parseDouble(field_ValorAluguel.getText()));
   locacao.setDataDevolucao(field_DataDevolucao.getText());
   locacao.setDataLocacao(field_DataLocacao.getText());
   locacao.setIdItensLocacao(Integer.parseInt(field_IdItensLocacao.getText()));
   locacao.setIdCliente(Integer.parseInt(field_IdCliente.getText()));
   
    return true;
}//fim preencherLocacao()

public boolean limparCampos(){
 label_IdLocacao.setText("0");
 field_ValorAluguel.setText("");
 field_DataLocacao.setText("");
 field_DataDevolucao.setText("");
 field_IdItensLocacao.setText("");
 field_IdCliente.setText("");
 
 field_Pesquisar.setText("");
 
 Table_Locacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Valor da Locação", "Data de Locação", "Data de Devolução", "ID Itens", "ID do Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    return true;
}

public boolean salvarDesabilitarBotoesCampos(){
    field_ValorAluguel.setEditable(false);
    field_DataDevolucao.setEditable(false);
    field_IdItensLocacao.setEditable(false);
    field_IdCliente.setEditable(false);
    
    btn_Salvar.setEnabled(false);
    btn_Editar.setEnabled(false);
    btn_Excluir.setEnabled(false);
    btn_Cancelar.setEnabled(false);
    
    limparCampos();
    return true;
}
}
