/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package.Views;

/**
 *
 * @author Milton Matias
 */
public class ReservaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReservaView
     */
    public ReservaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_idReserva = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        field_dataReserva = new javax.swing.JTextField();
        field_dataPrevista = new javax.swing.JTextField();
        field_valorReserva = new javax.swing.JTextField();
        field_iditem = new javax.swing.JTextField();
        field_idCliente = new javax.swing.JTextField();
        field_pesquisa = new javax.swing.JTextField();
        btn_pesquisa = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Reserva = new javax.swing.JTable();
        BackGround = new javax.swing.JLabel();

        setTitle("Realizar Reserva");

        jPanel1.setLayout(null);

        label_idReserva.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_idReserva.setText("0");
        jPanel1.add(label_idReserva);
        label_idReserva.setBounds(1000, 170, 100, 22);

        label_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_id.setText("Código:");
        jPanel1.add(label_id);
        label_id.setBounds(920, 170, 70, 22);

        field_dataReserva.setEditable(false);
        jPanel1.add(field_dataReserva);
        field_dataReserva.setBounds(340, 160, 250, 40);

        field_dataPrevista.setEditable(false);
        field_dataPrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_dataPrevistaActionPerformed(evt);
            }
        });
        jPanel1.add(field_dataPrevista);
        field_dataPrevista.setBounds(620, 160, 250, 40);

        field_valorReserva.setEditable(false);
        jPanel1.add(field_valorReserva);
        field_valorReserva.setBounds(340, 260, 250, 40);

        field_iditem.setEditable(false);
        jPanel1.add(field_iditem);
        field_iditem.setBounds(620, 260, 160, 40);

        field_idCliente.setEditable(false);
        jPanel1.add(field_idCliente);
        field_idCliente.setBounds(890, 260, 420, 40);
        jPanel1.add(field_pesquisa);
        field_pesquisa.setBounds(360, 390, 530, 40);

        btn_pesquisa.setText("Pesquisar");
        jPanel1.add(btn_pesquisa);
        btn_pesquisa.setBounds(910, 390, 120, 40);

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_novo);
        btn_novo.setBounds(130, 490, 150, 50);

        btn_Salvar.setText("Salvar");
        jPanel1.add(btn_Salvar);
        btn_Salvar.setBounds(130, 550, 150, 50);

        btn_editar.setText("Editar");
        jPanel1.add(btn_editar);
        btn_editar.setBounds(130, 610, 150, 50);

        btn_excluir.setText("Excluir");
        jPanel1.add(btn_excluir);
        btn_excluir.setBounds(130, 670, 150, 50);

        btn_cancelar.setText("Cancelar");
        jPanel1.add(btn_cancelar);
        btn_cancelar.setBounds(130, 730, 150, 50);

        btn_fechar.setText("Fechar");
        jPanel1.add(btn_fechar);
        btn_fechar.setBounds(1400, 730, 130, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data da Reserva:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 130, 160, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Prevista:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 130, 150, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor da Reserva:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 230, 170, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código do Item:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 230, 150, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cliente:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(890, 230, 100, 22);

        table_Reserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data da Reserva", "Data Prevista", "Valor da Reserva", "Código do Item", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_Reserva);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 470, 1010, 310);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Tela-Cadastrar-Cliente.png"))); // NOI18N
        jPanel1.add(BackGround);
        BackGround.setBounds(0, 0, 1580, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_dataPrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_dataPrevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_dataPrevistaActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        field_dataReserva.setEditable(true);
        field_dataPrevista.setEditable(true);
        field_valorReserva.setEditable(true);
        field_iditem.setEditable(true);
        field_idCliente.setEditable(true);
    }//GEN-LAST:event_btn_novoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_pesquisa;
    private javax.swing.JTextField field_dataPrevista;
    private javax.swing.JTextField field_dataReserva;
    private javax.swing.JTextField field_idCliente;
    private javax.swing.JTextField field_iditem;
    private javax.swing.JTextField field_pesquisa;
    private javax.swing.JTextField field_valorReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_idReserva;
    private javax.swing.JTable table_Reserva;
    // End of variables declaration//GEN-END:variables
}
