/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package.Views;

/**
 *
 * @author Milton Matias
 */
public class TelaMenuInicio extends javax.swing.JFrame {

    
    /**
     * Creates new form TelaMenuInicio
     */
    public TelaMenuInicio() {
        initComponents();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jButtonLocacao = new javax.swing.JButton();
        jButtonReserva = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jButtonJogos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItemJogos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Locação Rental Games");
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        DesktopPane.setPreferredSize(new java.awt.Dimension(1600, 900));

        jButtonLocacao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonLocacao.setText("Locação");
        jButtonLocacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocacaoActionPerformed(evt);
            }
        });
        DesktopPane.add(jButtonLocacao);
        jButtonLocacao.setBounds(390, 500, 180, 90);

        jButtonReserva.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonReserva.setText("Reservas");
        jButtonReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DesktopPane.add(jButtonReserva);
        jButtonReserva.setBounds(590, 500, 180, 90);

        jButtonCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonCliente.setText("Clientes");
        jButtonCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });
        DesktopPane.add(jButtonCliente);
        jButtonCliente.setBounds(790, 500, 180, 90);

        jButtonJogos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonJogos.setText("Jogos");
        jButtonJogos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogosActionPerformed(evt);
            }
        });
        DesktopPane.add(jButtonJogos);
        jButtonJogos.setBounds(990, 500, 180, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Tela-Menu-Model.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        DesktopPane.add(jLabel1);
        jLabel1.setBounds(0, 0, 1610, 830);

        jMenu3.setText("File");

        jMenuItem1.setText("Locação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Realizar Reserva");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Clientes");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Funcionário");
        jMenu3.add(jMenuItem4);

        jMenuItemJogos.setText("Jogos");
        jMenuItemJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJogosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemJogos);
        jMenu3.add(jSeparator1);

        jMenuItem6.setText("Sair");
        jMenu3.add(jMenuItem6);
        jMenu3.add(jSeparator2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJogosActionPerformed
        // TODO add your handling code here:
        JogoView jogoView = new JogoView();
        this.DesktopPane.add(jogoView);
        jogoView.setVisible(true);
    }//GEN-LAST:event_jMenuItemJogosActionPerformed

    private void jButtonLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLocacaoActionPerformed

    private void jButtonJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogosActionPerformed
        // TODO add your handling code here:
        JogoView jogoView = new JogoView();
        this.DesktopPane.add(jogoView);
        jogoView.setVisible(true);
    }//GEN-LAST:event_jButtonJogosActionPerformed

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        // TODO add your handling code here:
        ClienteView clienteView = new ClienteView();
        this.DesktopPane.add(clienteView);
        clienteView.setVisible(true);
    }//GEN-LAST:event_jButtonClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonJogos;
    private javax.swing.JButton jButtonLocacao;
    private javax.swing.JButton jButtonReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemJogos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
